name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Greeting prints “Привіт, <name>!”
      id: greeting-prints-name
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: pip install -r requirements.txt
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GREETING-PRINTS-NAME_RESULTS: "${{steps.greeting-prints-name.outputs.result}}"
      with:
        runners: greeting-prints-name
